x=0:0.5:50;
y=5*x.^2;
subplot(2,2,1);
plot(x,y);
title("Polynomial");
ylabel("y");
grid;
subplot(2,2,2);
semilogx(x,y);
title("Polynomial log/lineer");
ylabel("y"); grid;
subplot(2,2,3);
semilogy(x,y);
title("Polynomial lineer/log");
xlabel("x"); ylabel("y"); grid;
subplot(2,2,4);
loglog(x,y);
title("Polynomial log/log");
xlabel("x"); ylabel("y"); grid;